version: '2.0'
services:

  kserve:
    build: ./kserve
    ports:
      - 8080:8080
    volumes:
      - ./model/NERtagger/:/app/model/NERtagger
    container_name: kserve
    command: 'python app.py'

  jupyter:
    build: ./jupyter
    ports:
    - 8888:8888
    - 5151:5151
    volumes:
      - ./notebooks/:/app/notebooks
    container_name: jupyter
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  tensorboard:
    build: ./tensorboard
    ports:
    - 6006:6006
    volumes:
      - ./model/:/app/model
    container_name: tensorboard