apiVersion: v1
kind: Service
metadata:
  name: kserve-ds-cloud-test
spec:
  type: Nodeport
  selector:
    app: kserve-ds-cloud-test
  ports:
    - port: 8080
      nodePort: 30180
      targetPort: http
      protocol: TCP
      name: http